// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtbDh00OmRmjb1g5wbIx44aw-5x4rItKg',
    appId: '1:920296700438:web:39cc343d8877fe0bccd337',
    messagingSenderId: '920296700438',
    projectId: 'modern-high-school-2683e',
    authDomain: 'modern-high-school-2683e.firebaseapp.com',
    storageBucket: 'modern-high-school-2683e.firebasestorage.app',
    measurementId: 'G-9PHK4ZEH5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-q-vW9Uu1-WEeJdjv9F-manyNqPOU-8',
    appId: '1:920296700438:android:0e641a11fca76edbccd337',
    messagingSenderId: '920296700438',
    projectId: 'modern-high-school-2683e',
    storageBucket: 'modern-high-school-2683e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKdujvnQPtwBa1AYichR8ZfH5Ocmd84HM',
    appId: '1:920296700438:ios:99e97347af6c8809ccd337',
    messagingSenderId: '920296700438',
    projectId: 'modern-high-school-2683e',
    storageBucket: 'modern-high-school-2683e.firebasestorage.app',
    iosBundleId: 'com.example.modernHighSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKdujvnQPtwBa1AYichR8ZfH5Ocmd84HM',
    appId: '1:920296700438:ios:99e97347af6c8809ccd337',
    messagingSenderId: '920296700438',
    projectId: 'modern-high-school-2683e',
    storageBucket: 'modern-high-school-2683e.firebasestorage.app',
    iosBundleId: 'com.example.modernHighSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtbDh00OmRmjb1g5wbIx44aw-5x4rItKg',
    appId: '1:920296700438:web:816da0275a0a4431ccd337',
    messagingSenderId: '920296700438',
    projectId: 'modern-high-school-2683e',
    authDomain: 'modern-high-school-2683e.firebaseapp.com',
    storageBucket: 'modern-high-school-2683e.firebasestorage.app',
    measurementId: 'G-98EZB0R89L',
  );
}
